# Generated by Django 4.2.26 on 2025-11-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='文字描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='物品图片')),
                ('category', models.CharField(choices=[('electronics', '电子产品'), ('clothing', '服装'), ('documents', '文件'), ('jewelry', '首饰'), ('others', '其他')], default='others', max_length=50, verbose_name='物品种类')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='物品价值')),
                ('location', models.CharField(max_length=200, verbose_name='存放位置')),
                ('storage_time', models.DateTimeField(auto_now_add=True, verbose_name='存放时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-storage_time'],
            },
        ),
    ]
