# Generated by Django 4.2.26 on 2025-11-27 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furniture_code', models.PositiveIntegerField(unique=True, verbose_name='家具编码')),
                ('furniture_name', models.CharField(max_length=50, verbose_name='家具名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '家具',
                'verbose_name_plural': '家具',
                'ordering': ['furniture_name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=1, unique=True, verbose_name='房间编码')),
                ('room_name', models.CharField(max_length=50, verbose_name='房间名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['room_name'],
            },
        ),
        migrations.CreateModel(
            name='StorageCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.PositiveIntegerField(verbose_name='储物格基础编号')),
                ('cell_id', models.CharField(max_length=7, unique=True, verbose_name='储物格唯一标识')),
                ('qr_code', models.BinaryField(verbose_name='二维码')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_cells', to='items.furniture', verbose_name='家具')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_cells', to='items.room', verbose_name='房间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_cells', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '储物格',
                'verbose_name_plural': '储物格',
                'ordering': ['room', 'furniture', 'cell_number'],
                'unique_together': {('room', 'furniture', 'cell_number')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=50, unique=True, verbose_name='物品编号')),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='文字描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='物品图片')),
                ('category', models.CharField(choices=[('electronics', '电子产品'), ('clothing', '服装'), ('documents', '文件'), ('jewelry', '首饰'), ('others', '其他')], default='others', max_length=50, verbose_name='物品种类')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='物品价值')),
                ('location', models.CharField(max_length=200, verbose_name='存放位置')),
                ('storage_time', models.DateTimeField(auto_now_add=True, verbose_name='存放时间')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('qr_code', models.TextField(blank=True, null=True, verbose_name='二维码')),
                ('storage_cells', models.ManyToManyField(blank=True, related_name='items', to='items.storagecell', verbose_name='存放的储物格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'ordering': ['-storage_time'],
            },
        ),
    ]
