# Generated by Django 4.2.26 on 2025-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        # 清理可能存在的孤立外键行，防止删除模型时触发完整性检查失败
        migrations.RunSQL(
            sql=[
                # 删除指向不存在 StorageCell 的 item-storage 链接
                "DELETE FROM items_item_storage_cells WHERE storagecell_id NOT IN (SELECT id FROM items_storagecell);",
                # 删除指向不存在 Furniture 的 StorageCell 行
                "DELETE FROM items_storagecell WHERE furniture_id NOT IN (SELECT id FROM items_furniture);",
                # 删除指向不存在 Room 的 StorageCell 行
                "DELETE FROM items_storagecell WHERE room_id NOT IN (SELECT id FROM items_room);",
                # 删除可能存在的旧表 items_item_storages 中引用的行（旧模型残留）
                "DELETE FROM items_item_storages WHERE storage_id NOT IN (SELECT id FROM items_storage);",
                # 清空 items_item_storages（如果存在旧引用，会导致删除 Furniture 表时触发约束）
                "DELETE FROM items_item_storages;",
                # 清空 items_storage（旧模型残留的表）以避免在删除 Furniture 表时出现外键引用
                "DELETE FROM items_storage;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 先删除Item模型中与其他模型的关联字段
        migrations.RemoveField(
            model_name='item',
            name='storage_cells',
        ),
        # 删除Item模型中的其他字段
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='value',
        ),
        # 修改Item模型的字段
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='物品编号'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='存放位置'),
        ),
        # 删除StorageCell模型
        migrations.DeleteModel(
            name='StorageCell',
        ),
        # 删除Furniture模型
        migrations.DeleteModel(
            name='Furniture',
        ),
        # 删除Room模型
        migrations.DeleteModel(
            name='Room',
        ),
    ]
