# Generated by Django 4.2.26 on 2025-11-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='物品编号'),
        ),
    ]
