# Generated by Django 4.2.26 on 2025-11-25 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0002_item_item_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='储物格编号')),
                ('name', models.CharField(max_length=200, verbose_name='储物格名称')),
                ('room', models.CharField(max_length=100, verbose_name='房间')),
                ('furniture', models.CharField(max_length=100, verbose_name='家具')),
                ('unit', models.CharField(max_length=100, verbose_name='储物格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '储物格',
                'verbose_name_plural': '储物格',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='storages',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.storage', verbose_name='存放的储物格'),
        ),
    ]
