# Generated by Django 4.2.26 on 2025-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_storage_item_storages'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='二维码'),
        ),
    ]
