# Generated by Django 4.2.26 on 2025-12-03 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_item_category_alter_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='导航名称')),
                ('type', models.CharField(choices=[('main', '大分类'), ('sub', '子标签')], max_length=10, verbose_name='导航类型')),
                ('url', models.CharField(max_length=200, verbose_name='导航链接')),
                ('icon', models.CharField(max_length=20, verbose_name='导航图标')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序顺序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='items.navigation', verbose_name='父级导航')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '导航',
                'verbose_name_plural': '导航',
                'ordering': ['order', 'id'],
                'unique_together': {('user', 'name', 'type', 'parent')},
            },
        ),
    ]
