# Generated by Django 4.2.26 on 2025-11-25 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='物品编号'),
            preserve_default=False,
        ),
    ]
