# Generated by Django 4.2.26 on 2025-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_item_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ['room', 'furniture', 'storage_code'], 'verbose_name': '储物格', 'verbose_name_plural': '储物格'},
        ),
        migrations.RemoveField(
            model_name='storage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='unit',
        ),
        migrations.AddField(
            model_name='storage',
            name='qr_code',
            field=models.BinaryField(default=b'', verbose_name='二维码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='storage_code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='储物格编号'),
            preserve_default=False,
        ),
    ]
