# Generated by Django 4.2.26 on 2025-11-25 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_storage_data(apps, schema_editor):
    """迁移现有储物格数据，创建对应的Room和Furniture实例"""
    Storage = apps.get_model('items', 'Storage')
    Room = apps.get_model('items', 'Room')
    Furniture = apps.get_model('items', 'Furniture')
    
    # 遍历所有储物格记录
    for storage in Storage.objects.all():
        # 获取旧的字符串值
        room_name = storage.room
        furniture_name = storage.furniture
        
        if room_name and furniture_name:
            # 创建或获取对应的Room实例
            room, _ = Room.objects.get_or_create(
                name=room_name,
                user=storage.user
            )
            
            # 创建或获取对应的Furniture实例
            furniture, _ = Furniture.objects.get_or_create(
                name=furniture_name,
                user=storage.user
            )
            
            # 更新储物格记录的新外键字段
            storage.room_new = room
            storage.furniture_new = furniture
            storage.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_alter_storage_options_remove_storage_created_at_and_more'),
    ]

    operations = [
        # 1. 创建Room和Furniture模型
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='房间名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '房间',
                'verbose_name_plural': '房间',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='家具名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '家具',
                'verbose_name_plural': '家具',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        # 2. 为Storage模型添加新的外键字段，允许为空
        migrations.AddField(
            model_name='storage',
            name='room_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='items.room', null=True, verbose_name='新房间'),
        ),
        migrations.AddField(
            model_name='storage',
            name='furniture_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='items.furniture', null=True, verbose_name='新家具'),
        ),
        # 3. 运行数据迁移函数，将旧的字符串值转换为外键关系
        migrations.RunPython(migrate_storage_data),
        # 4. 删除旧的字符串字段
        migrations.RemoveField(
            model_name='storage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='furniture',
        ),
        # 5. 删除那些没有有效外键值的储物格记录
        migrations.RunSQL(
            "DELETE FROM items_storage WHERE room_new_id IS NULL OR furniture_new_id IS NULL;",
            reverse_sql=""
        ),
        # 6. 将新的外键字段重命名为原来的字段名
        migrations.RenameField(
            model_name='storage',
            old_name='room_new',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='furniture_new',
            new_name='furniture',
        ),
        # 7. 更新外键字段的related_name
        migrations.AlterField(
            model_name='storage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='items.room', verbose_name='房间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='items.furniture', verbose_name='家具'),
            preserve_default=False,
        ),
    ]
