# Generated by Django 4.2.26 on 2025-11-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_room_furniture_alter_storage_furniture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_code',
            field=models.CharField(max_length=50, verbose_name='储物格编号'),
        ),
    ]
