# Generated by Django 4.2.26 on 2025-11-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_alter_storage_storage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='家具字母标识'),
        ),
        migrations.AddField(
            model_name='room',
            name='letter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='房间字母标识'),
        ),
    ]
