# Generated by Django 4.2.26 on 2025-11-25 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0009_furniture_letter_room_letter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together={('storage_code', 'user')},
        ),
    ]
