# Generated by Django 4.2.26 on 2025-11-27 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('wechat', '微信'), ('qq', 'QQ'), ('alipay', '支付宝'), ('supabase', 'Supabase')], max_length=20, verbose_name='认证提供商')),
                ('openid', models.CharField(max_length=100, verbose_name='第三方唯一标识')),
                ('unionid', models.CharField(blank=True, max_length=100, null=True, verbose_name='统一标识（微信）')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='访问令牌')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='刷新令牌')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('user_info', models.JSONField(default=dict, verbose_name='用户信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '第三方认证信息',
                'verbose_name_plural': '第三方认证信息',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='alipay_userid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付宝用户ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_third_party_user',
            field=models.BooleanField(default=False, verbose_name='是否第三方登录用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='QQ OpenID'),
        ),
        migrations.AddField(
            model_name='user',
            name='supabase_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Supabase用户ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_user_phone_9474e8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['wechat_openid'], name='users_user_wechat__640083_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['qq_openid'], name='users_user_qq_open_43ab18_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['alipay_userid'], name='users_user_alipay__8eeb1b_idx'),
        ),
        migrations.AddField(
            model_name='thirdpartyauth',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_auths', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddIndex(
            model_name='thirdpartyauth',
            index=models.Index(fields=['provider', 'openid'], name='users_third_provide_e83ba1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='thirdpartyauth',
            unique_together={('user', 'provider')},
        ),
    ]
