import sqlite3, os
DB = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'db.sqlite3')
conn = sqlite3.connect(DB)
c = conn.cursor()
print('Furniture ids:')
c.execute('SELECT id FROM items_furniture ORDER BY id LIMIT 20')
print(c.fetchall())
print('items_storage rows (first 20):')
c.execute('SELECT id, furniture_id, room_id, storage_code FROM items_storage ORDER BY id LIMIT 20')
print(c.fetchall())
print('items_storagecell rows (first 20):')
c.execute('SELECT id, furniture_id, room_id, cell_id FROM items_storagecell ORDER BY id LIMIT 20')
print(c.fetchall())
conn.close()
